import { food } from "./app/shared/models/food";
import { tag } from "./app/shared/models/tag";
export const sample_foods: food[]=[
{id:'1',
name:'Burgar',
price:11,
cookTime:'20-30',
favorite:false,
origin:['asia','India'],
stars:5,
tags:['FastFood','Burgar','Lunch'],
imageUrl:'/assets/images/1.jpg'
},
{id:'2',
name:'Pizza',
price:12,
cookTime:'20-30',
favorite:false,
origin:['asia','Japan'],
stars:4,
tags:['FastFood','Pizza','Lunch'],
imageUrl:'/assets/images/2.jpg'
},
{id:'3',
name:'Meat Ball',
price:11,
cookTime:'20-30',
favorite:false,
origin:['asia','Afghanistan'],
stars:5,
tags:['FastFood','Meat Ball','Lunch'],
imageUrl:'/assets/images/3.jpg'
},
{id:'4',
name:'Rice',
price:11,
cookTime:'20-30',
favorite:false,
origin:['asia','Pakistan'],
stars:1,
tags:['Fry','Rice','Lunch'],
imageUrl:'/assets/images/4.jpg'
},
{id:'5',
name:'Biryani',
price:11,
cookTime:'20-30',
favorite:false,
origin:['asia','India'],
stars:5,
tags:['Hamburger','Biryani','Lunch'],
imageUrl:'/assets/images/5.jpg'
},
{id:'6',
name:'Checken soup',
price:11,
cookTime:'20-30',
favorite:false,
origin:['asia','India'],
stars:5,
tags:['slowFood','checken soup','Lunch'],
imageUrl:'/assets/images/6.jpg'
},
{id:'7',
name:'Pani Pori',
price:11,
cookTime:'20-30',
favorite:false,
origin:['asia','India'],
stars:5,
tags:['Hamburger','Pani Pori','Lunch'],
imageUrl:'/assets/images/7.jpg'
},

]
export const sample_tags:tag[] = [
  { name: 'All', count: 6 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]
